;=====================
; 功能支持说明 - 最后更新：2025-05-29
;=====================
;去广告：不支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
;显示IP归属地应用伪装：不支持

;=====================
; Fix规则
;=====================
ruleset=🌐 国外流量,https://raw.githubusercontent.com/ruich-4/mihomo/main/Ruleset/Proxy.list
ruleset=🌐 国外流量,https://raw.githubusercontent.com/ruich-4/mihomo/main/Ruleset/Steam.list
ruleset=🌐 国外流量,https://raw.githubusercontent.com/ruich-4/mihomo/main/Ruleset/Anti-fraud.list
ruleset=🏠 国内流量,https://raw.githubusercontent.com/ruich-4/mihomo/heads/main/Ruleset/Direct.list

;=====================
; 加密交易所
;=====================
ruleset=🪙 交易所,[]GEOSITE,okx
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,okx
ruleset=🪙 交易所,[]GEOSITE,binance
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,binance
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,binance
ruleset=🪙 交易所,[]GEOSITE,bybit
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,bybit
ruleset=🪙 交易所,[]DOMAIN-SUFFIX,bnw3w.com
ruleset=🪙 交易所,[]DOMAIN-SUFFIX,cloudfront.net
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,ffbbbdc6d3c353211fe2ba39c9f744cd
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,ffe390afd658c19dcbf707e0597b846d
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,axiom
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,sintral
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,meme
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,safepal
ruleset=🪙 交易所,[]DOMAIN-KEYWORD,telemetry

;=====================
; AI 分流
;=====================
ruleset=🤖 AI,[]GEOSITE,cursor
ruleset=🤖 AI,https://raw.githubusercontent.com/ruich-4/mihomo/main/Ruleset/AI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Oracle/Oracle.list

;=====================
; Google 服务
;=====================
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list

;=====================
; 区域解锁
;=====================
ruleset=🔓 区域解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TruthSocial/TruthSocial.list
ruleset=🔓 区域解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list

;=====================
; Play商店 / Google FCM
;=====================
ruleset=📱 Play商店,https://raw.githubusercontent.com/ruich-4/mihomo/main/Ruleset/Play.list
ruleset=📡 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

;=====================
; 巴哈姆特
;=====================
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list

;=====================
; Gfwlist
;=====================
ruleset=🌐 国外流量,[]GEOSITE,gfw
ruleset=🌐 国外流量,https://raw.githubusercontent.com/ruich-4/mihomo/heads/main/Ruleset/gfw-ip.list

;=====================
; 国内流量
;=====================
ruleset=🏠 国内流量,[]GEOSITE,paypal
ruleset=🏠 国内流量,[]GEOSITE,apple@cn
ruleset=🏠 国内流量,[]GEOSITE,apple-cn
ruleset=🏠 国内流量,[]GEOSITE,icloud@cn
ruleset=🏠 国内流量,[]GEOSITE,microsoft@cn
ruleset=🏠 国内流量,[]GEOSITE,geolocation-cn
ruleset=🏠 国内流量,[]GEOSITE,category-games@cn
ruleset=🏠 国内流量,[]GEOIP,private
ruleset=🏠 国内流量,[]GEOIP,cn

;=====================
; 国外流量
;=====================
ruleset=🌐 国外流量,[]GEOSITE,geolocation-!cn

;=====================
; 漏网之鱼
;=====================
ruleset=🐟 漏网之鱼,[]FINAL


;=====================
; 策略组定义
;=====================
custom_proxy_group=🌐 国外流量`select`[]♻️ 自动选择`[]🔄 故障转移`[]⚙️ 自建节点`[]✈️ 主动选择`[]🛩️ 备用选择
custom_proxy_group=🏠 国内流量`select`[]DIRECT`(电信|联通|移动|北京|上海|广州|深圳)`[]✈️ 主动选择`[]🛩️ 备用选择
custom_proxy_group=✈️ 主动选择`select`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]⚙️ 自建节点
custom_proxy_group=🛩️ 备用选择`select`.*
custom_proxy_group=🔍 Google`select`[]♻️ 自动选择`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇺🇸 美国节点`[]✈️ 主动选择`[]🛩️ 备用选择
custom_proxy_group=🤖 AI`select`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇺🇸 美国节点`[]⚙️ 自建节点`[]✈️ 主动选择`[]🛩️ 备用选择
custom_proxy_group=📺 巴哈姆特`select`[]🇭🇰 香港节点`[]🇹🇼 台湾节点
custom_proxy_group=📡 谷歌FCM`select`[]🏠 国内流量`[]🌐 国外流量`[]✈️ 主动选择
custom_proxy_group=📱 Play商店`select`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点
custom_proxy_group=🪙 交易所`select`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点
custom_proxy_group=🔓 区域解锁`select`[]🇺🇸 美国节点`[]✈️ 主动选择
custom_proxy_group=🐟 漏网之鱼`select`[]🌐 国外流量`[]🏠 国内流量`[]✈️ 主动选择`[]🛩️ 备用选择

;=====================
; 自动测速与健康检查策略
;=====================
custom_proxy_group=♻️ 自动选择`url-test`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`https://www.google.com/generate_204`300,,50
custom_proxy_group=⚙️ 自建节点`url-test`(自建)`https://www.google.cn/generate_204`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`https://www.google.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`https://www.google.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`https://www.google.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`https://www.google.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`https://www.google.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`https://www.google.com/generate_204`300,,150
custom_proxy_group=🔄 故障转移`fallback`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`https://www.google.com/generate_204`300,,50

;=====================
; 规则生成功能设置
;=====================
enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/ruich-4/mihomo/main/base.ini
